// Copyright 2026, compose-miuix-ui contributors
// SPDX-License-Identifier: Apache-2.0

package utils

import androidx.compose.ui.graphics.vector.ImageVector
import top.yukonga.miuix.kmp.icon.MiuixIcons
import top.yukonga.miuix.kmp.icon.os4.Add
import top.yukonga.miuix.kmp.icon.os4.AddBookmark
import top.yukonga.miuix.kmp.icon.os4.AddCircle
import top.yukonga.miuix.kmp.icon.os4.AddFolder
import top.yukonga.miuix.kmp.icon.os4.AiScan
import top.yukonga.miuix.kmp.icon.os4.Alarm
import top.yukonga.miuix.kmp.icon.os4.Album
import top.yukonga.miuix.kmp.icon.os4.All
import top.yukonga.miuix.kmp.icon.os4.Answer
import top.yukonga.miuix.kmp.icon.os4.AppRecording
import top.yukonga.miuix.kmp.icon.os4.Back
import top.yukonga.miuix.kmp.icon.os4.Background
import top.yukonga.miuix.kmp.icon.os4.Backup
import top.yukonga.miuix.kmp.icon.os4.BankCards
import top.yukonga.miuix.kmp.icon.os4.Blocklist
import top.yukonga.miuix.kmp.icon.os4.Book
import top.yukonga.miuix.kmp.icon.os4.CallRecording
import top.yukonga.miuix.kmp.icon.os4.Carrier
import top.yukonga.miuix.kmp.icon.os4.ChevronBackward
import top.yukonga.miuix.kmp.icon.os4.ChevronForward
import top.yukonga.miuix.kmp.icon.os4.Child
import top.yukonga.miuix.kmp.icon.os4.Clear
import top.yukonga.miuix.kmp.icon.os4.Close
import top.yukonga.miuix.kmp.icon.os4.Close2
import top.yukonga.miuix.kmp.icon.os4.CloudFill
import top.yukonga.miuix.kmp.icon.os4.Community
import top.yukonga.miuix.kmp.icon.os4.Contacts
import top.yukonga.miuix.kmp.icon.os4.ContactsBook
import top.yukonga.miuix.kmp.icon.os4.ContactsCircle
import top.yukonga.miuix.kmp.icon.os4.ConvertFile
import top.yukonga.miuix.kmp.icon.os4.Copy
import top.yukonga.miuix.kmp.icon.os4.Coupon
import top.yukonga.miuix.kmp.icon.os4.Create
import top.yukonga.miuix.kmp.icon.os4.Cut
import top.yukonga.miuix.kmp.icon.os4.Delete
import top.yukonga.miuix.kmp.icon.os4.Download
import top.yukonga.miuix.kmp.icon.os4.Edit
import top.yukonga.miuix.kmp.icon.os4.Email
import top.yukonga.miuix.kmp.icon.os4.ExpandLess
import top.yukonga.miuix.kmp.icon.os4.ExpandMore
import top.yukonga.miuix.kmp.icon.os4.Favorites
import top.yukonga.miuix.kmp.icon.os4.FavoritesFill
import top.yukonga.miuix.kmp.icon.os4.File
import top.yukonga.miuix.kmp.icon.os4.FileDownloads
import top.yukonga.miuix.kmp.icon.os4.Filter
import top.yukonga.miuix.kmp.icon.os4.Folder
import top.yukonga.miuix.kmp.icon.os4.FolderFill
import top.yukonga.miuix.kmp.icon.os4.Forward
import top.yukonga.miuix.kmp.icon.os4.Gift
import top.yukonga.miuix.kmp.icon.os4.GridView
import top.yukonga.miuix.kmp.icon.os4.Help
import top.yukonga.miuix.kmp.icon.os4.Hide
import top.yukonga.miuix.kmp.icon.os4.HorizontalSplit
import top.yukonga.miuix.kmp.icon.os4.Image
import top.yukonga.miuix.kmp.icon.os4.Import
import top.yukonga.miuix.kmp.icon.os4.Info
import top.yukonga.miuix.kmp.icon.os4.InsufficientCloudStorageSpace
import top.yukonga.miuix.kmp.icon.os4.Layers
import top.yukonga.miuix.kmp.icon.os4.Link
import top.yukonga.miuix.kmp.icon.os4.ListView
import top.yukonga.miuix.kmp.icon.os4.Location
import top.yukonga.miuix.kmp.icon.os4.Lock
import top.yukonga.miuix.kmp.icon.os4.MapAlbum
import top.yukonga.miuix.kmp.icon.os4.MarkAllAsRead
import top.yukonga.miuix.kmp.icon.os4.MarkAsRead
import top.yukonga.miuix.kmp.icon.os4.MarkRasUnread
import top.yukonga.miuix.kmp.icon.os4.MemoryFunction
import top.yukonga.miuix.kmp.icon.os4.Menu
import top.yukonga.miuix.kmp.icon.os4.Merge
import top.yukonga.miuix.kmp.icon.os4.Messages
import top.yukonga.miuix.kmp.icon.os4.Mic
import top.yukonga.miuix.kmp.icon.os4.MicSlash
import top.yukonga.miuix.kmp.icon.os4.MindMap
import top.yukonga.miuix.kmp.icon.os4.MiniDrama
import top.yukonga.miuix.kmp.icon.os4.Months
import top.yukonga.miuix.kmp.icon.os4.More
import top.yukonga.miuix.kmp.icon.os4.MoreCircle
import top.yukonga.miuix.kmp.icon.os4.MoveFile
import top.yukonga.miuix.kmp.icon.os4.Movie
import top.yukonga.miuix.kmp.icon.os4.Music
import top.yukonga.miuix.kmp.icon.os4.Notes
import top.yukonga.miuix.kmp.icon.os4.NotesFill
import top.yukonga.miuix.kmp.icon.os4.Notifications
import top.yukonga.miuix.kmp.icon.os4.Ok
import top.yukonga.miuix.kmp.icon.os4.Paste
import top.yukonga.miuix.kmp.icon.os4.Pause
import top.yukonga.miuix.kmp.icon.os4.Phone
import top.yukonga.miuix.kmp.icon.os4.Photos
import top.yukonga.miuix.kmp.icon.os4.Pin
import top.yukonga.miuix.kmp.icon.os4.Play
import top.yukonga.miuix.kmp.icon.os4.Playlist
import top.yukonga.miuix.kmp.icon.os4.Promotions
import top.yukonga.miuix.kmp.icon.os4.Read
import top.yukonga.miuix.kmp.icon.os4.Recent
import top.yukonga.miuix.kmp.icon.os4.Recording
import top.yukonga.miuix.kmp.icon.os4.RecordingTape
import top.yukonga.miuix.kmp.icon.os4.Redo
import top.yukonga.miuix.kmp.icon.os4.Refresh
import top.yukonga.miuix.kmp.icon.os4.Remove
import top.yukonga.miuix.kmp.icon.os4.RemoveContact
import top.yukonga.miuix.kmp.icon.os4.Rename
import top.yukonga.miuix.kmp.icon.os4.Replace
import top.yukonga.miuix.kmp.icon.os4.Reply
import top.yukonga.miuix.kmp.icon.os4.ReplyAll
import top.yukonga.miuix.kmp.icon.os4.Report
import top.yukonga.miuix.kmp.icon.os4.Reset
import top.yukonga.miuix.kmp.icon.os4.Rocket
import top.yukonga.miuix.kmp.icon.os4.RotateLeft
import top.yukonga.miuix.kmp.icon.os4.Save
import top.yukonga.miuix.kmp.icon.os4.Scan
import top.yukonga.miuix.kmp.icon.os4.ScreenCapture
import top.yukonga.miuix.kmp.icon.os4.ScreenMirroring
import top.yukonga.miuix.kmp.icon.os4.Search
import top.yukonga.miuix.kmp.icon.os4.SearchDevice
import top.yukonga.miuix.kmp.icon.os4.SelectAll
import top.yukonga.miuix.kmp.icon.os4.Send
import top.yukonga.miuix.kmp.icon.os4.Settings
import top.yukonga.miuix.kmp.icon.os4.Share
import top.yukonga.miuix.kmp.icon.os4.ShortVideo
import top.yukonga.miuix.kmp.icon.os4.Show
import top.yukonga.miuix.kmp.icon.os4.Sidebar
import top.yukonga.miuix.kmp.icon.os4.Sort
import top.yukonga.miuix.kmp.icon.os4.Starred
import top.yukonga.miuix.kmp.icon.os4.Stopwatch
import top.yukonga.miuix.kmp.icon.os4.Store
import top.yukonga.miuix.kmp.icon.os4.Tasks
import top.yukonga.miuix.kmp.icon.os4.Th1
import top.yukonga.miuix.kmp.icon.os4.Th10
import top.yukonga.miuix.kmp.icon.os4.Th11
import top.yukonga.miuix.kmp.icon.os4.Th12
import top.yukonga.miuix.kmp.icon.os4.Th13
import top.yukonga.miuix.kmp.icon.os4.Th14
import top.yukonga.miuix.kmp.icon.os4.Th15
import top.yukonga.miuix.kmp.icon.os4.Th16
import top.yukonga.miuix.kmp.icon.os4.Th17
import top.yukonga.miuix.kmp.icon.os4.Th18
import top.yukonga.miuix.kmp.icon.os4.Th19
import top.yukonga.miuix.kmp.icon.os4.Th2
import top.yukonga.miuix.kmp.icon.os4.Th20
import top.yukonga.miuix.kmp.icon.os4.Th21
import top.yukonga.miuix.kmp.icon.os4.Th22
import top.yukonga.miuix.kmp.icon.os4.Th23
import top.yukonga.miuix.kmp.icon.os4.Th24
import top.yukonga.miuix.kmp.icon.os4.Th25
import top.yukonga.miuix.kmp.icon.os4.Th26
import top.yukonga.miuix.kmp.icon.os4.Th27
import top.yukonga.miuix.kmp.icon.os4.Th28
import top.yukonga.miuix.kmp.icon.os4.Th29
import top.yukonga.miuix.kmp.icon.os4.Th3
import top.yukonga.miuix.kmp.icon.os4.Th30
import top.yukonga.miuix.kmp.icon.os4.Th31
import top.yukonga.miuix.kmp.icon.os4.Th4
import top.yukonga.miuix.kmp.icon.os4.Th5
import top.yukonga.miuix.kmp.icon.os4.Th6
import top.yukonga.miuix.kmp.icon.os4.Th7
import top.yukonga.miuix.kmp.icon.os4.Th8
import top.yukonga.miuix.kmp.icon.os4.Th9
import top.yukonga.miuix.kmp.icon.os4.Theme
import top.yukonga.miuix.kmp.icon.os4.Timer
import top.yukonga.miuix.kmp.icon.os4.TopDownloads
import top.yukonga.miuix.kmp.icon.os4.Translate
import top.yukonga.miuix.kmp.icon.os4.Trim
import top.yukonga.miuix.kmp.icon.os4.Tune
import top.yukonga.miuix.kmp.icon.os4.Undo
import top.yukonga.miuix.kmp.icon.os4.Unlock
import top.yukonga.miuix.kmp.icon.os4.Unpin
import top.yukonga.miuix.kmp.icon.os4.Unstar
import top.yukonga.miuix.kmp.icon.os4.Update
import top.yukonga.miuix.kmp.icon.os4.UploadCloud
import top.yukonga.miuix.kmp.icon.os4.VerticalSplit
import top.yukonga.miuix.kmp.icon.os4.VolumeOff
import top.yukonga.miuix.kmp.icon.os4.VolumeUp
import top.yukonga.miuix.kmp.icon.os4.Weeks
import top.yukonga.miuix.kmp.icon.os4.WorldClock
import top.yukonga.miuix.kmp.icon.os4.Years
import top.yukonga.miuix.kmp.icon.os4.ZoomOut

val MiuixIcons.Os4.All: Map<String, List<ImageVector>> by lazy {
    mapOf(
        "Light" to listOf(
            MiuixIcons.Os4.Light.Add,
            MiuixIcons.Os4.Light.AddBookmark,
            MiuixIcons.Os4.Light.AddCircle,
            MiuixIcons.Os4.Light.AddFolder,
            MiuixIcons.Os4.Light.AiScan,
            MiuixIcons.Os4.Light.Alarm,
            MiuixIcons.Os4.Light.Album,
            MiuixIcons.Os4.Light.All,
            MiuixIcons.Os4.Light.Answer,
            MiuixIcons.Os4.Light.AppRecording,
            MiuixIcons.Os4.Light.Back,
            MiuixIcons.Os4.Light.Background,
            MiuixIcons.Os4.Light.Backup,
            MiuixIcons.Os4.Light.BankCards,
            MiuixIcons.Os4.Light.Blocklist,
            MiuixIcons.Os4.Light.Book,
            MiuixIcons.Os4.Light.CallRecording,
            MiuixIcons.Os4.Light.Carrier,
            MiuixIcons.Os4.Light.ChevronBackward,
            MiuixIcons.Os4.Light.ChevronForward,
            MiuixIcons.Os4.Light.Child,
            MiuixIcons.Os4.Light.Clear,
            MiuixIcons.Os4.Light.Close,
            MiuixIcons.Os4.Light.Close2,
            MiuixIcons.Os4.Light.CloudFill,
            MiuixIcons.Os4.Light.Community,
            MiuixIcons.Os4.Light.Contacts,
            MiuixIcons.Os4.Light.ContactsBook,
            MiuixIcons.Os4.Light.ContactsCircle,
            MiuixIcons.Os4.Light.ConvertFile,
            MiuixIcons.Os4.Light.Copy,
            MiuixIcons.Os4.Light.Coupon,
            MiuixIcons.Os4.Light.Create,
            MiuixIcons.Os4.Light.Cut,
            MiuixIcons.Os4.Light.Delete,
            MiuixIcons.Os4.Light.Download,
            MiuixIcons.Os4.Light.Edit,
            MiuixIcons.Os4.Light.Email,
            MiuixIcons.Os4.Light.ExpandLess,
            MiuixIcons.Os4.Light.ExpandMore,
            MiuixIcons.Os4.Light.Favorites,
            MiuixIcons.Os4.Light.FavoritesFill,
            MiuixIcons.Os4.Light.File,
            MiuixIcons.Os4.Light.FileDownloads,
            MiuixIcons.Os4.Light.Filter,
            MiuixIcons.Os4.Light.Folder,
            MiuixIcons.Os4.Light.FolderFill,
            MiuixIcons.Os4.Light.Forward,
            MiuixIcons.Os4.Light.Gift,
            MiuixIcons.Os4.Light.GridView,
            MiuixIcons.Os4.Light.Help,
            MiuixIcons.Os4.Light.Hide,
            MiuixIcons.Os4.Light.HorizontalSplit,
            MiuixIcons.Os4.Light.Image,
            MiuixIcons.Os4.Light.Import,
            MiuixIcons.Os4.Light.Info,
            MiuixIcons.Os4.Light.InsufficientCloudStorageSpace,
            MiuixIcons.Os4.Light.Layers,
            MiuixIcons.Os4.Light.Link,
            MiuixIcons.Os4.Light.ListView,
            MiuixIcons.Os4.Light.Location,
            MiuixIcons.Os4.Light.Lock,
            MiuixIcons.Os4.Light.MapAlbum,
            MiuixIcons.Os4.Light.MarkAllAsRead,
            MiuixIcons.Os4.Light.MarkAsRead,
            MiuixIcons.Os4.Light.MarkRasUnread,
            MiuixIcons.Os4.Light.MemoryFunction,
            MiuixIcons.Os4.Light.Menu,
            MiuixIcons.Os4.Light.Merge,
            MiuixIcons.Os4.Light.Messages,
            MiuixIcons.Os4.Light.Mic,
            MiuixIcons.Os4.Light.MicSlash,
            MiuixIcons.Os4.Light.MindMap,
            MiuixIcons.Os4.Light.MiniDrama,
            MiuixIcons.Os4.Light.Months,
            MiuixIcons.Os4.Light.More,
            MiuixIcons.Os4.Light.MoreCircle,
            MiuixIcons.Os4.Light.MoveFile,
            MiuixIcons.Os4.Light.Movie,
            MiuixIcons.Os4.Light.Music,
            MiuixIcons.Os4.Light.Notes,
            MiuixIcons.Os4.Light.NotesFill,
            MiuixIcons.Os4.Light.Notifications,
            MiuixIcons.Os4.Light.Ok,
            MiuixIcons.Os4.Light.Paste,
            MiuixIcons.Os4.Light.Pause,
            MiuixIcons.Os4.Light.Phone,
            MiuixIcons.Os4.Light.Photos,
            MiuixIcons.Os4.Light.Pin,
            MiuixIcons.Os4.Light.Play,
            MiuixIcons.Os4.Light.Playlist,
            MiuixIcons.Os4.Light.Promotions,
            MiuixIcons.Os4.Light.Read,
            MiuixIcons.Os4.Light.Recent,
            MiuixIcons.Os4.Light.Recording,
            MiuixIcons.Os4.Light.RecordingTape,
            MiuixIcons.Os4.Light.Redo,
            MiuixIcons.Os4.Light.Refresh,
            MiuixIcons.Os4.Light.Remove,
            MiuixIcons.Os4.Light.RemoveContact,
            MiuixIcons.Os4.Light.Rename,
            MiuixIcons.Os4.Light.Replace,
            MiuixIcons.Os4.Light.Reply,
            MiuixIcons.Os4.Light.ReplyAll,
            MiuixIcons.Os4.Light.Report,
            MiuixIcons.Os4.Light.Reset,
            MiuixIcons.Os4.Light.Rocket,
            MiuixIcons.Os4.Light.RotateLeft,
            MiuixIcons.Os4.Light.Save,
            MiuixIcons.Os4.Light.Scan,
            MiuixIcons.Os4.Light.ScreenCapture,
            MiuixIcons.Os4.Light.ScreenMirroring,
            MiuixIcons.Os4.Light.Search,
            MiuixIcons.Os4.Light.SearchDevice,
            MiuixIcons.Os4.Light.SelectAll,
            MiuixIcons.Os4.Light.Send,
            MiuixIcons.Os4.Light.Settings,
            MiuixIcons.Os4.Light.Share,
            MiuixIcons.Os4.Light.ShortVideo,
            MiuixIcons.Os4.Light.Show,
            MiuixIcons.Os4.Light.Sidebar,
            MiuixIcons.Os4.Light.Sort,
            MiuixIcons.Os4.Light.Starred,
            MiuixIcons.Os4.Light.Stopwatch,
            MiuixIcons.Os4.Light.Store,
            MiuixIcons.Os4.Light.Tasks,
            MiuixIcons.Os4.Light.Th1,
            MiuixIcons.Os4.Light.Th10,
            MiuixIcons.Os4.Light.Th11,
            MiuixIcons.Os4.Light.Th12,
            MiuixIcons.Os4.Light.Th13,
            MiuixIcons.Os4.Light.Th14,
            MiuixIcons.Os4.Light.Th15,
            MiuixIcons.Os4.Light.Th16,
            MiuixIcons.Os4.Light.Th17,
            MiuixIcons.Os4.Light.Th18,
            MiuixIcons.Os4.Light.Th19,
            MiuixIcons.Os4.Light.Th2,
            MiuixIcons.Os4.Light.Th20,
            MiuixIcons.Os4.Light.Th21,
            MiuixIcons.Os4.Light.Th22,
            MiuixIcons.Os4.Light.Th23,
            MiuixIcons.Os4.Light.Th24,
            MiuixIcons.Os4.Light.Th25,
            MiuixIcons.Os4.Light.Th26,
            MiuixIcons.Os4.Light.Th27,
            MiuixIcons.Os4.Light.Th28,
            MiuixIcons.Os4.Light.Th29,
            MiuixIcons.Os4.Light.Th3,
            MiuixIcons.Os4.Light.Th30,
            MiuixIcons.Os4.Light.Th31,
            MiuixIcons.Os4.Light.Th4,
            MiuixIcons.Os4.Light.Th5,
            MiuixIcons.Os4.Light.Th6,
            MiuixIcons.Os4.Light.Th7,
            MiuixIcons.Os4.Light.Th8,
            MiuixIcons.Os4.Light.Th9,
            MiuixIcons.Os4.Light.Theme,
            MiuixIcons.Os4.Light.Timer,
            MiuixIcons.Os4.Light.TopDownloads,
            MiuixIcons.Os4.Light.Translate,
            MiuixIcons.Os4.Light.Trim,
            MiuixIcons.Os4.Light.Tune,
            MiuixIcons.Os4.Light.Undo,
            MiuixIcons.Os4.Light.Unlock,
            MiuixIcons.Os4.Light.Unpin,
            MiuixIcons.Os4.Light.Unstar,
            MiuixIcons.Os4.Light.Update,
            MiuixIcons.Os4.Light.UploadCloud,
            MiuixIcons.Os4.Light.VerticalSplit,
            MiuixIcons.Os4.Light.VolumeOff,
            MiuixIcons.Os4.Light.VolumeUp,
            MiuixIcons.Os4.Light.Weeks,
            MiuixIcons.Os4.Light.WorldClock,
            MiuixIcons.Os4.Light.Years,
            MiuixIcons.Os4.Light.ZoomOut,
        ),
        "Normal" to listOf(
            MiuixIcons.Os4.Normal.Add,
            MiuixIcons.Os4.Normal.AddBookmark,
            MiuixIcons.Os4.Normal.AddCircle,
            MiuixIcons.Os4.Normal.AddFolder,
            MiuixIcons.Os4.Normal.AiScan,
            MiuixIcons.Os4.Normal.Alarm,
            MiuixIcons.Os4.Normal.Album,
            MiuixIcons.Os4.Normal.All,
            MiuixIcons.Os4.Normal.Answer,
            MiuixIcons.Os4.Normal.AppRecording,
            MiuixIcons.Os4.Normal.Back,
            MiuixIcons.Os4.Normal.Background,
            MiuixIcons.Os4.Normal.Backup,
            MiuixIcons.Os4.Normal.BankCards,
            MiuixIcons.Os4.Normal.Blocklist,
            MiuixIcons.Os4.Normal.Book,
            MiuixIcons.Os4.Normal.CallRecording,
            MiuixIcons.Os4.Normal.Carrier,
            MiuixIcons.Os4.Normal.ChevronBackward,
            MiuixIcons.Os4.Normal.ChevronForward,
            MiuixIcons.Os4.Normal.Child,
            MiuixIcons.Os4.Normal.Clear,
            MiuixIcons.Os4.Normal.Close,
            MiuixIcons.Os4.Normal.Close2,
            MiuixIcons.Os4.Normal.CloudFill,
            MiuixIcons.Os4.Normal.Community,
            MiuixIcons.Os4.Normal.Contacts,
            MiuixIcons.Os4.Normal.ContactsBook,
            MiuixIcons.Os4.Normal.ContactsCircle,
            MiuixIcons.Os4.Normal.ConvertFile,
            MiuixIcons.Os4.Normal.Copy,
            MiuixIcons.Os4.Normal.Coupon,
            MiuixIcons.Os4.Normal.Create,
            MiuixIcons.Os4.Normal.Cut,
            MiuixIcons.Os4.Normal.Delete,
            MiuixIcons.Os4.Normal.Download,
            MiuixIcons.Os4.Normal.Edit,
            MiuixIcons.Os4.Normal.Email,
            MiuixIcons.Os4.Normal.ExpandLess,
            MiuixIcons.Os4.Normal.ExpandMore,
            MiuixIcons.Os4.Normal.Favorites,
            MiuixIcons.Os4.Normal.FavoritesFill,
            MiuixIcons.Os4.Normal.File,
            MiuixIcons.Os4.Normal.FileDownloads,
            MiuixIcons.Os4.Normal.Filter,
            MiuixIcons.Os4.Normal.Folder,
            MiuixIcons.Os4.Normal.FolderFill,
            MiuixIcons.Os4.Normal.Forward,
            MiuixIcons.Os4.Normal.Gift,
            MiuixIcons.Os4.Normal.GridView,
            MiuixIcons.Os4.Normal.Help,
            MiuixIcons.Os4.Normal.Hide,
            MiuixIcons.Os4.Normal.HorizontalSplit,
            MiuixIcons.Os4.Normal.Image,
            MiuixIcons.Os4.Normal.Import,
            MiuixIcons.Os4.Normal.Info,
            MiuixIcons.Os4.Normal.InsufficientCloudStorageSpace,
            MiuixIcons.Os4.Normal.Layers,
            MiuixIcons.Os4.Normal.Link,
            MiuixIcons.Os4.Normal.ListView,
            MiuixIcons.Os4.Normal.Location,
            MiuixIcons.Os4.Normal.Lock,
            MiuixIcons.Os4.Normal.MapAlbum,
            MiuixIcons.Os4.Normal.MarkAllAsRead,
            MiuixIcons.Os4.Normal.MarkAsRead,
            MiuixIcons.Os4.Normal.MarkRasUnread,
            MiuixIcons.Os4.Normal.MemoryFunction,
            MiuixIcons.Os4.Normal.Menu,
            MiuixIcons.Os4.Normal.Merge,
            MiuixIcons.Os4.Normal.Messages,
            MiuixIcons.Os4.Normal.Mic,
            MiuixIcons.Os4.Normal.MicSlash,
            MiuixIcons.Os4.Normal.MindMap,
            MiuixIcons.Os4.Normal.MiniDrama,
            MiuixIcons.Os4.Normal.Months,
            MiuixIcons.Os4.Normal.More,
            MiuixIcons.Os4.Normal.MoreCircle,
            MiuixIcons.Os4.Normal.MoveFile,
            MiuixIcons.Os4.Normal.Movie,
            MiuixIcons.Os4.Normal.Music,
            MiuixIcons.Os4.Normal.Notes,
            MiuixIcons.Os4.Normal.NotesFill,
            MiuixIcons.Os4.Normal.Notifications,
            MiuixIcons.Os4.Normal.Ok,
            MiuixIcons.Os4.Normal.Paste,
            MiuixIcons.Os4.Normal.Pause,
            MiuixIcons.Os4.Normal.Phone,
            MiuixIcons.Os4.Normal.Photos,
            MiuixIcons.Os4.Normal.Pin,
            MiuixIcons.Os4.Normal.Play,
            MiuixIcons.Os4.Normal.Playlist,
            MiuixIcons.Os4.Normal.Promotions,
            MiuixIcons.Os4.Normal.Read,
            MiuixIcons.Os4.Normal.Recent,
            MiuixIcons.Os4.Normal.Recording,
            MiuixIcons.Os4.Normal.RecordingTape,
            MiuixIcons.Os4.Normal.Redo,
            MiuixIcons.Os4.Normal.Refresh,
            MiuixIcons.Os4.Normal.Remove,
            MiuixIcons.Os4.Normal.RemoveContact,
            MiuixIcons.Os4.Normal.Rename,
            MiuixIcons.Os4.Normal.Replace,
            MiuixIcons.Os4.Normal.Reply,
            MiuixIcons.Os4.Normal.ReplyAll,
            MiuixIcons.Os4.Normal.Report,
            MiuixIcons.Os4.Normal.Reset,
            MiuixIcons.Os4.Normal.Rocket,
            MiuixIcons.Os4.Normal.RotateLeft,
            MiuixIcons.Os4.Normal.Save,
            MiuixIcons.Os4.Normal.Scan,
            MiuixIcons.Os4.Normal.ScreenCapture,
            MiuixIcons.Os4.Normal.ScreenMirroring,
            MiuixIcons.Os4.Normal.Search,
            MiuixIcons.Os4.Normal.SearchDevice,
            MiuixIcons.Os4.Normal.SelectAll,
            MiuixIcons.Os4.Normal.Send,
            MiuixIcons.Os4.Normal.Settings,
            MiuixIcons.Os4.Normal.Share,
            MiuixIcons.Os4.Normal.ShortVideo,
            MiuixIcons.Os4.Normal.Show,
            MiuixIcons.Os4.Normal.Sidebar,
            MiuixIcons.Os4.Normal.Sort,
            MiuixIcons.Os4.Normal.Starred,
            MiuixIcons.Os4.Normal.Stopwatch,
            MiuixIcons.Os4.Normal.Store,
            MiuixIcons.Os4.Normal.Tasks,
            MiuixIcons.Os4.Normal.Th1,
            MiuixIcons.Os4.Normal.Th10,
            MiuixIcons.Os4.Normal.Th11,
            MiuixIcons.Os4.Normal.Th12,
            MiuixIcons.Os4.Normal.Th13,
            MiuixIcons.Os4.Normal.Th14,
            MiuixIcons.Os4.Normal.Th15,
            MiuixIcons.Os4.Normal.Th16,
            MiuixIcons.Os4.Normal.Th17,
            MiuixIcons.Os4.Normal.Th18,
            MiuixIcons.Os4.Normal.Th19,
            MiuixIcons.Os4.Normal.Th2,
            MiuixIcons.Os4.Normal.Th20,
            MiuixIcons.Os4.Normal.Th21,
            MiuixIcons.Os4.Normal.Th22,
            MiuixIcons.Os4.Normal.Th23,
            MiuixIcons.Os4.Normal.Th24,
            MiuixIcons.Os4.Normal.Th25,
            MiuixIcons.Os4.Normal.Th26,
            MiuixIcons.Os4.Normal.Th27,
            MiuixIcons.Os4.Normal.Th28,
            MiuixIcons.Os4.Normal.Th29,
            MiuixIcons.Os4.Normal.Th3,
            MiuixIcons.Os4.Normal.Th30,
            MiuixIcons.Os4.Normal.Th31,
            MiuixIcons.Os4.Normal.Th4,
            MiuixIcons.Os4.Normal.Th5,
            MiuixIcons.Os4.Normal.Th6,
            MiuixIcons.Os4.Normal.Th7,
            MiuixIcons.Os4.Normal.Th8,
            MiuixIcons.Os4.Normal.Th9,
            MiuixIcons.Os4.Normal.Theme,
            MiuixIcons.Os4.Normal.Timer,
            MiuixIcons.Os4.Normal.TopDownloads,
            MiuixIcons.Os4.Normal.Translate,
            MiuixIcons.Os4.Normal.Trim,
            MiuixIcons.Os4.Normal.Tune,
            MiuixIcons.Os4.Normal.Undo,
            MiuixIcons.Os4.Normal.Unlock,
            MiuixIcons.Os4.Normal.Unpin,
            MiuixIcons.Os4.Normal.Unstar,
            MiuixIcons.Os4.Normal.Update,
            MiuixIcons.Os4.Normal.UploadCloud,
            MiuixIcons.Os4.Normal.VerticalSplit,
            MiuixIcons.Os4.Normal.VolumeOff,
            MiuixIcons.Os4.Normal.VolumeUp,
            MiuixIcons.Os4.Normal.Weeks,
            MiuixIcons.Os4.Normal.WorldClock,
            MiuixIcons.Os4.Normal.Years,
            MiuixIcons.Os4.Normal.ZoomOut,
        ),
        "Regular" to listOf(
            MiuixIcons.Os4.Regular.Add,
            MiuixIcons.Os4.Regular.AddBookmark,
            MiuixIcons.Os4.Regular.AddCircle,
            MiuixIcons.Os4.Regular.AddFolder,
            MiuixIcons.Os4.Regular.AiScan,
            MiuixIcons.Os4.Regular.Alarm,
            MiuixIcons.Os4.Regular.Album,
            MiuixIcons.Os4.Regular.All,
            MiuixIcons.Os4.Regular.Answer,
            MiuixIcons.Os4.Regular.AppRecording,
            MiuixIcons.Os4.Regular.Back,
            MiuixIcons.Os4.Regular.Background,
            MiuixIcons.Os4.Regular.Backup,
            MiuixIcons.Os4.Regular.BankCards,
            MiuixIcons.Os4.Regular.Blocklist,
            MiuixIcons.Os4.Regular.Book,
            MiuixIcons.Os4.Regular.CallRecording,
            MiuixIcons.Os4.Regular.Carrier,
            MiuixIcons.Os4.Regular.ChevronBackward,
            MiuixIcons.Os4.Regular.ChevronForward,
            MiuixIcons.Os4.Regular.Child,
            MiuixIcons.Os4.Regular.Clear,
            MiuixIcons.Os4.Regular.Close,
            MiuixIcons.Os4.Regular.Close2,
            MiuixIcons.Os4.Regular.CloudFill,
            MiuixIcons.Os4.Regular.Community,
            MiuixIcons.Os4.Regular.Contacts,
            MiuixIcons.Os4.Regular.ContactsBook,
            MiuixIcons.Os4.Regular.ContactsCircle,
            MiuixIcons.Os4.Regular.ConvertFile,
            MiuixIcons.Os4.Regular.Copy,
            MiuixIcons.Os4.Regular.Coupon,
            MiuixIcons.Os4.Regular.Create,
            MiuixIcons.Os4.Regular.Cut,
            MiuixIcons.Os4.Regular.Delete,
            MiuixIcons.Os4.Regular.Download,
            MiuixIcons.Os4.Regular.Edit,
            MiuixIcons.Os4.Regular.Email,
            MiuixIcons.Os4.Regular.ExpandLess,
            MiuixIcons.Os4.Regular.ExpandMore,
            MiuixIcons.Os4.Regular.Favorites,
            MiuixIcons.Os4.Regular.FavoritesFill,
            MiuixIcons.Os4.Regular.File,
            MiuixIcons.Os4.Regular.FileDownloads,
            MiuixIcons.Os4.Regular.Filter,
            MiuixIcons.Os4.Regular.Folder,
            MiuixIcons.Os4.Regular.FolderFill,
            MiuixIcons.Os4.Regular.Forward,
            MiuixIcons.Os4.Regular.Gift,
            MiuixIcons.Os4.Regular.GridView,
            MiuixIcons.Os4.Regular.Help,
            MiuixIcons.Os4.Regular.Hide,
            MiuixIcons.Os4.Regular.HorizontalSplit,
            MiuixIcons.Os4.Regular.Image,
            MiuixIcons.Os4.Regular.Import,
            MiuixIcons.Os4.Regular.Info,
            MiuixIcons.Os4.Regular.InsufficientCloudStorageSpace,
            MiuixIcons.Os4.Regular.Layers,
            MiuixIcons.Os4.Regular.Link,
            MiuixIcons.Os4.Regular.ListView,
            MiuixIcons.Os4.Regular.Location,
            MiuixIcons.Os4.Regular.Lock,
            MiuixIcons.Os4.Regular.MapAlbum,
            MiuixIcons.Os4.Regular.MarkAllAsRead,
            MiuixIcons.Os4.Regular.MarkAsRead,
            MiuixIcons.Os4.Regular.MarkRasUnread,
            MiuixIcons.Os4.Regular.MemoryFunction,
            MiuixIcons.Os4.Regular.Menu,
            MiuixIcons.Os4.Regular.Merge,
            MiuixIcons.Os4.Regular.Messages,
            MiuixIcons.Os4.Regular.Mic,
            MiuixIcons.Os4.Regular.MicSlash,
            MiuixIcons.Os4.Regular.MindMap,
            MiuixIcons.Os4.Regular.MiniDrama,
            MiuixIcons.Os4.Regular.Months,
            MiuixIcons.Os4.Regular.More,
            MiuixIcons.Os4.Regular.MoreCircle,
            MiuixIcons.Os4.Regular.MoveFile,
            MiuixIcons.Os4.Regular.Movie,
            MiuixIcons.Os4.Regular.Music,
            MiuixIcons.Os4.Regular.Notes,
            MiuixIcons.Os4.Regular.NotesFill,
            MiuixIcons.Os4.Regular.Notifications,
            MiuixIcons.Os4.Regular.Ok,
            MiuixIcons.Os4.Regular.Paste,
            MiuixIcons.Os4.Regular.Pause,
            MiuixIcons.Os4.Regular.Phone,
            MiuixIcons.Os4.Regular.Photos,
            MiuixIcons.Os4.Regular.Pin,
            MiuixIcons.Os4.Regular.Play,
            MiuixIcons.Os4.Regular.Playlist,
            MiuixIcons.Os4.Regular.Promotions,
            MiuixIcons.Os4.Regular.Read,
            MiuixIcons.Os4.Regular.Recent,
            MiuixIcons.Os4.Regular.Recording,
            MiuixIcons.Os4.Regular.RecordingTape,
            MiuixIcons.Os4.Regular.Redo,
            MiuixIcons.Os4.Regular.Refresh,
            MiuixIcons.Os4.Regular.Remove,
            MiuixIcons.Os4.Regular.RemoveContact,
            MiuixIcons.Os4.Regular.Rename,
            MiuixIcons.Os4.Regular.Replace,
            MiuixIcons.Os4.Regular.Reply,
            MiuixIcons.Os4.Regular.ReplyAll,
            MiuixIcons.Os4.Regular.Report,
            MiuixIcons.Os4.Regular.Reset,
            MiuixIcons.Os4.Regular.Rocket,
            MiuixIcons.Os4.Regular.RotateLeft,
            MiuixIcons.Os4.Regular.Save,
            MiuixIcons.Os4.Regular.Scan,
            MiuixIcons.Os4.Regular.ScreenCapture,
            MiuixIcons.Os4.Regular.ScreenMirroring,
            MiuixIcons.Os4.Regular.Search,
            MiuixIcons.Os4.Regular.SearchDevice,
            MiuixIcons.Os4.Regular.SelectAll,
            MiuixIcons.Os4.Regular.Send,
            MiuixIcons.Os4.Regular.Settings,
            MiuixIcons.Os4.Regular.Share,
            MiuixIcons.Os4.Regular.ShortVideo,
            MiuixIcons.Os4.Regular.Show,
            MiuixIcons.Os4.Regular.Sidebar,
            MiuixIcons.Os4.Regular.Sort,
            MiuixIcons.Os4.Regular.Starred,
            MiuixIcons.Os4.Regular.Stopwatch,
            MiuixIcons.Os4.Regular.Store,
            MiuixIcons.Os4.Regular.Tasks,
            MiuixIcons.Os4.Regular.Th1,
            MiuixIcons.Os4.Regular.Th10,
            MiuixIcons.Os4.Regular.Th11,
            MiuixIcons.Os4.Regular.Th12,
            MiuixIcons.Os4.Regular.Th13,
            MiuixIcons.Os4.Regular.Th14,
            MiuixIcons.Os4.Regular.Th15,
            MiuixIcons.Os4.Regular.Th16,
            MiuixIcons.Os4.Regular.Th17,
            MiuixIcons.Os4.Regular.Th18,
            MiuixIcons.Os4.Regular.Th19,
            MiuixIcons.Os4.Regular.Th2,
            MiuixIcons.Os4.Regular.Th20,
            MiuixIcons.Os4.Regular.Th21,
            MiuixIcons.Os4.Regular.Th22,
            MiuixIcons.Os4.Regular.Th23,
            MiuixIcons.Os4.Regular.Th24,
            MiuixIcons.Os4.Regular.Th25,
            MiuixIcons.Os4.Regular.Th26,
            MiuixIcons.Os4.Regular.Th27,
            MiuixIcons.Os4.Regular.Th28,
            MiuixIcons.Os4.Regular.Th29,
            MiuixIcons.Os4.Regular.Th3,
            MiuixIcons.Os4.Regular.Th30,
            MiuixIcons.Os4.Regular.Th31,
            MiuixIcons.Os4.Regular.Th4,
            MiuixIcons.Os4.Regular.Th5,
            MiuixIcons.Os4.Regular.Th6,
            MiuixIcons.Os4.Regular.Th7,
            MiuixIcons.Os4.Regular.Th8,
            MiuixIcons.Os4.Regular.Th9,
            MiuixIcons.Os4.Regular.Theme,
            MiuixIcons.Os4.Regular.Timer,
            MiuixIcons.Os4.Regular.TopDownloads,
            MiuixIcons.Os4.Regular.Translate,
            MiuixIcons.Os4.Regular.Trim,
            MiuixIcons.Os4.Regular.Tune,
            MiuixIcons.Os4.Regular.Undo,
            MiuixIcons.Os4.Regular.Unlock,
            MiuixIcons.Os4.Regular.Unpin,
            MiuixIcons.Os4.Regular.Unstar,
            MiuixIcons.Os4.Regular.Update,
            MiuixIcons.Os4.Regular.UploadCloud,
            MiuixIcons.Os4.Regular.VerticalSplit,
            MiuixIcons.Os4.Regular.VolumeOff,
            MiuixIcons.Os4.Regular.VolumeUp,
            MiuixIcons.Os4.Regular.Weeks,
            MiuixIcons.Os4.Regular.WorldClock,
            MiuixIcons.Os4.Regular.Years,
            MiuixIcons.Os4.Regular.ZoomOut,
        ),
        "Medium" to listOf(
            MiuixIcons.Os4.Medium.Add,
            MiuixIcons.Os4.Medium.AddBookmark,
            MiuixIcons.Os4.Medium.AddCircle,
            MiuixIcons.Os4.Medium.AddFolder,
            MiuixIcons.Os4.Medium.AiScan,
            MiuixIcons.Os4.Medium.Alarm,
            MiuixIcons.Os4.Medium.Album,
            MiuixIcons.Os4.Medium.All,
            MiuixIcons.Os4.Medium.Answer,
            MiuixIcons.Os4.Medium.AppRecording,
            MiuixIcons.Os4.Medium.Back,
            MiuixIcons.Os4.Medium.Background,
            MiuixIcons.Os4.Medium.Backup,
            MiuixIcons.Os4.Medium.BankCards,
            MiuixIcons.Os4.Medium.Blocklist,
            MiuixIcons.Os4.Medium.Book,
            MiuixIcons.Os4.Medium.CallRecording,
            MiuixIcons.Os4.Medium.Carrier,
            MiuixIcons.Os4.Medium.ChevronBackward,
            MiuixIcons.Os4.Medium.ChevronForward,
            MiuixIcons.Os4.Medium.Child,
            MiuixIcons.Os4.Medium.Clear,
            MiuixIcons.Os4.Medium.Close,
            MiuixIcons.Os4.Medium.Close2,
            MiuixIcons.Os4.Medium.CloudFill,
            MiuixIcons.Os4.Medium.Community,
            MiuixIcons.Os4.Medium.Contacts,
            MiuixIcons.Os4.Medium.ContactsBook,
            MiuixIcons.Os4.Medium.ContactsCircle,
            MiuixIcons.Os4.Medium.ConvertFile,
            MiuixIcons.Os4.Medium.Copy,
            MiuixIcons.Os4.Medium.Coupon,
            MiuixIcons.Os4.Medium.Create,
            MiuixIcons.Os4.Medium.Cut,
            MiuixIcons.Os4.Medium.Delete,
            MiuixIcons.Os4.Medium.Download,
            MiuixIcons.Os4.Medium.Edit,
            MiuixIcons.Os4.Medium.Email,
            MiuixIcons.Os4.Medium.ExpandLess,
            MiuixIcons.Os4.Medium.ExpandMore,
            MiuixIcons.Os4.Medium.Favorites,
            MiuixIcons.Os4.Medium.FavoritesFill,
            MiuixIcons.Os4.Medium.File,
            MiuixIcons.Os4.Medium.FileDownloads,
            MiuixIcons.Os4.Medium.Filter,
            MiuixIcons.Os4.Medium.Folder,
            MiuixIcons.Os4.Medium.FolderFill,
            MiuixIcons.Os4.Medium.Forward,
            MiuixIcons.Os4.Medium.Gift,
            MiuixIcons.Os4.Medium.GridView,
            MiuixIcons.Os4.Medium.Help,
            MiuixIcons.Os4.Medium.Hide,
            MiuixIcons.Os4.Medium.HorizontalSplit,
            MiuixIcons.Os4.Medium.Image,
            MiuixIcons.Os4.Medium.Import,
            MiuixIcons.Os4.Medium.Info,
            MiuixIcons.Os4.Medium.InsufficientCloudStorageSpace,
            MiuixIcons.Os4.Medium.Layers,
            MiuixIcons.Os4.Medium.Link,
            MiuixIcons.Os4.Medium.ListView,
            MiuixIcons.Os4.Medium.Location,
            MiuixIcons.Os4.Medium.Lock,
            MiuixIcons.Os4.Medium.MapAlbum,
            MiuixIcons.Os4.Medium.MarkAllAsRead,
            MiuixIcons.Os4.Medium.MarkAsRead,
            MiuixIcons.Os4.Medium.MarkRasUnread,
            MiuixIcons.Os4.Medium.MemoryFunction,
            MiuixIcons.Os4.Medium.Menu,
            MiuixIcons.Os4.Medium.Merge,
            MiuixIcons.Os4.Medium.Messages,
            MiuixIcons.Os4.Medium.Mic,
            MiuixIcons.Os4.Medium.MicSlash,
            MiuixIcons.Os4.Medium.MindMap,
            MiuixIcons.Os4.Medium.MiniDrama,
            MiuixIcons.Os4.Medium.Months,
            MiuixIcons.Os4.Medium.More,
            MiuixIcons.Os4.Medium.MoreCircle,
            MiuixIcons.Os4.Medium.MoveFile,
            MiuixIcons.Os4.Medium.Movie,
            MiuixIcons.Os4.Medium.Music,
            MiuixIcons.Os4.Medium.Notes,
            MiuixIcons.Os4.Medium.NotesFill,
            MiuixIcons.Os4.Medium.Notifications,
            MiuixIcons.Os4.Medium.Ok,
            MiuixIcons.Os4.Medium.Paste,
            MiuixIcons.Os4.Medium.Pause,
            MiuixIcons.Os4.Medium.Phone,
            MiuixIcons.Os4.Medium.Photos,
            MiuixIcons.Os4.Medium.Pin,
            MiuixIcons.Os4.Medium.Play,
            MiuixIcons.Os4.Medium.Playlist,
            MiuixIcons.Os4.Medium.Promotions,
            MiuixIcons.Os4.Medium.Read,
            MiuixIcons.Os4.Medium.Recent,
            MiuixIcons.Os4.Medium.Recording,
            MiuixIcons.Os4.Medium.RecordingTape,
            MiuixIcons.Os4.Medium.Redo,
            MiuixIcons.Os4.Medium.Refresh,
            MiuixIcons.Os4.Medium.Remove,
            MiuixIcons.Os4.Medium.RemoveContact,
            MiuixIcons.Os4.Medium.Rename,
            MiuixIcons.Os4.Medium.Replace,
            MiuixIcons.Os4.Medium.Reply,
            MiuixIcons.Os4.Medium.ReplyAll,
            MiuixIcons.Os4.Medium.Report,
            MiuixIcons.Os4.Medium.Reset,
            MiuixIcons.Os4.Medium.Rocket,
            MiuixIcons.Os4.Medium.RotateLeft,
            MiuixIcons.Os4.Medium.Save,
            MiuixIcons.Os4.Medium.Scan,
            MiuixIcons.Os4.Medium.ScreenCapture,
            MiuixIcons.Os4.Medium.ScreenMirroring,
            MiuixIcons.Os4.Medium.Search,
            MiuixIcons.Os4.Medium.SearchDevice,
            MiuixIcons.Os4.Medium.SelectAll,
            MiuixIcons.Os4.Medium.Send,
            MiuixIcons.Os4.Medium.Settings,
            MiuixIcons.Os4.Medium.Share,
            MiuixIcons.Os4.Medium.ShortVideo,
            MiuixIcons.Os4.Medium.Show,
            MiuixIcons.Os4.Medium.Sidebar,
            MiuixIcons.Os4.Medium.Sort,
            MiuixIcons.Os4.Medium.Starred,
            MiuixIcons.Os4.Medium.Stopwatch,
            MiuixIcons.Os4.Medium.Store,
            MiuixIcons.Os4.Medium.Tasks,
            MiuixIcons.Os4.Medium.Th1,
            MiuixIcons.Os4.Medium.Th10,
            MiuixIcons.Os4.Medium.Th11,
            MiuixIcons.Os4.Medium.Th12,
            MiuixIcons.Os4.Medium.Th13,
            MiuixIcons.Os4.Medium.Th14,
            MiuixIcons.Os4.Medium.Th15,
            MiuixIcons.Os4.Medium.Th16,
            MiuixIcons.Os4.Medium.Th17,
            MiuixIcons.Os4.Medium.Th18,
            MiuixIcons.Os4.Medium.Th19,
            MiuixIcons.Os4.Medium.Th2,
            MiuixIcons.Os4.Medium.Th20,
            MiuixIcons.Os4.Medium.Th21,
            MiuixIcons.Os4.Medium.Th22,
            MiuixIcons.Os4.Medium.Th23,
            MiuixIcons.Os4.Medium.Th24,
            MiuixIcons.Os4.Medium.Th25,
            MiuixIcons.Os4.Medium.Th26,
            MiuixIcons.Os4.Medium.Th27,
            MiuixIcons.Os4.Medium.Th28,
            MiuixIcons.Os4.Medium.Th29,
            MiuixIcons.Os4.Medium.Th3,
            MiuixIcons.Os4.Medium.Th30,
            MiuixIcons.Os4.Medium.Th31,
            MiuixIcons.Os4.Medium.Th4,
            MiuixIcons.Os4.Medium.Th5,
            MiuixIcons.Os4.Medium.Th6,
            MiuixIcons.Os4.Medium.Th7,
            MiuixIcons.Os4.Medium.Th8,
            MiuixIcons.Os4.Medium.Th9,
            MiuixIcons.Os4.Medium.Theme,
            MiuixIcons.Os4.Medium.Timer,
            MiuixIcons.Os4.Medium.TopDownloads,
            MiuixIcons.Os4.Medium.Translate,
            MiuixIcons.Os4.Medium.Trim,
            MiuixIcons.Os4.Medium.Tune,
            MiuixIcons.Os4.Medium.Undo,
            MiuixIcons.Os4.Medium.Unlock,
            MiuixIcons.Os4.Medium.Unpin,
            MiuixIcons.Os4.Medium.Unstar,
            MiuixIcons.Os4.Medium.Update,
            MiuixIcons.Os4.Medium.UploadCloud,
            MiuixIcons.Os4.Medium.VerticalSplit,
            MiuixIcons.Os4.Medium.VolumeOff,
            MiuixIcons.Os4.Medium.VolumeUp,
            MiuixIcons.Os4.Medium.Weeks,
            MiuixIcons.Os4.Medium.WorldClock,
            MiuixIcons.Os4.Medium.Years,
            MiuixIcons.Os4.Medium.ZoomOut,
        ),
        "Demibold" to listOf(
            MiuixIcons.Os4.Demibold.Add,
            MiuixIcons.Os4.Demibold.AddBookmark,
            MiuixIcons.Os4.Demibold.AddCircle,
            MiuixIcons.Os4.Demibold.AddFolder,
            MiuixIcons.Os4.Demibold.AiScan,
            MiuixIcons.Os4.Demibold.Alarm,
            MiuixIcons.Os4.Demibold.Album,
            MiuixIcons.Os4.Demibold.All,
            MiuixIcons.Os4.Demibold.Answer,
            MiuixIcons.Os4.Demibold.AppRecording,
            MiuixIcons.Os4.Demibold.Back,
            MiuixIcons.Os4.Demibold.Background,
            MiuixIcons.Os4.Demibold.Backup,
            MiuixIcons.Os4.Demibold.BankCards,
            MiuixIcons.Os4.Demibold.Blocklist,
            MiuixIcons.Os4.Demibold.Book,
            MiuixIcons.Os4.Demibold.CallRecording,
            MiuixIcons.Os4.Demibold.Carrier,
            MiuixIcons.Os4.Demibold.ChevronBackward,
            MiuixIcons.Os4.Demibold.ChevronForward,
            MiuixIcons.Os4.Demibold.Child,
            MiuixIcons.Os4.Demibold.Clear,
            MiuixIcons.Os4.Demibold.Close,
            MiuixIcons.Os4.Demibold.Close2,
            MiuixIcons.Os4.Demibold.CloudFill,
            MiuixIcons.Os4.Demibold.Community,
            MiuixIcons.Os4.Demibold.Contacts,
            MiuixIcons.Os4.Demibold.ContactsBook,
            MiuixIcons.Os4.Demibold.ContactsCircle,
            MiuixIcons.Os4.Demibold.ConvertFile,
            MiuixIcons.Os4.Demibold.Copy,
            MiuixIcons.Os4.Demibold.Coupon,
            MiuixIcons.Os4.Demibold.Create,
            MiuixIcons.Os4.Demibold.Cut,
            MiuixIcons.Os4.Demibold.Delete,
            MiuixIcons.Os4.Demibold.Download,
            MiuixIcons.Os4.Demibold.Edit,
            MiuixIcons.Os4.Demibold.Email,
            MiuixIcons.Os4.Demibold.ExpandLess,
            MiuixIcons.Os4.Demibold.ExpandMore,
            MiuixIcons.Os4.Demibold.Favorites,
            MiuixIcons.Os4.Demibold.FavoritesFill,
            MiuixIcons.Os4.Demibold.File,
            MiuixIcons.Os4.Demibold.FileDownloads,
            MiuixIcons.Os4.Demibold.Filter,
            MiuixIcons.Os4.Demibold.Folder,
            MiuixIcons.Os4.Demibold.FolderFill,
            MiuixIcons.Os4.Demibold.Forward,
            MiuixIcons.Os4.Demibold.Gift,
            MiuixIcons.Os4.Demibold.GridView,
            MiuixIcons.Os4.Demibold.Help,
            MiuixIcons.Os4.Demibold.Hide,
            MiuixIcons.Os4.Demibold.HorizontalSplit,
            MiuixIcons.Os4.Demibold.Image,
            MiuixIcons.Os4.Demibold.Import,
            MiuixIcons.Os4.Demibold.Info,
            MiuixIcons.Os4.Demibold.InsufficientCloudStorageSpace,
            MiuixIcons.Os4.Demibold.Layers,
            MiuixIcons.Os4.Demibold.Link,
            MiuixIcons.Os4.Demibold.ListView,
            MiuixIcons.Os4.Demibold.Location,
            MiuixIcons.Os4.Demibold.Lock,
            MiuixIcons.Os4.Demibold.MapAlbum,
            MiuixIcons.Os4.Demibold.MarkAllAsRead,
            MiuixIcons.Os4.Demibold.MarkAsRead,
            MiuixIcons.Os4.Demibold.MarkRasUnread,
            MiuixIcons.Os4.Demibold.MemoryFunction,
            MiuixIcons.Os4.Demibold.Menu,
            MiuixIcons.Os4.Demibold.Merge,
            MiuixIcons.Os4.Demibold.Messages,
            MiuixIcons.Os4.Demibold.Mic,
            MiuixIcons.Os4.Demibold.MicSlash,
            MiuixIcons.Os4.Demibold.MindMap,
            MiuixIcons.Os4.Demibold.MiniDrama,
            MiuixIcons.Os4.Demibold.Months,
            MiuixIcons.Os4.Demibold.More,
            MiuixIcons.Os4.Demibold.MoreCircle,
            MiuixIcons.Os4.Demibold.MoveFile,
            MiuixIcons.Os4.Demibold.Movie,
            MiuixIcons.Os4.Demibold.Music,
            MiuixIcons.Os4.Demibold.Notes,
            MiuixIcons.Os4.Demibold.NotesFill,
            MiuixIcons.Os4.Demibold.Notifications,
            MiuixIcons.Os4.Demibold.Ok,
            MiuixIcons.Os4.Demibold.Paste,
            MiuixIcons.Os4.Demibold.Pause,
            MiuixIcons.Os4.Demibold.Phone,
            MiuixIcons.Os4.Demibold.Photos,
            MiuixIcons.Os4.Demibold.Pin,
            MiuixIcons.Os4.Demibold.Play,
            MiuixIcons.Os4.Demibold.Playlist,
            MiuixIcons.Os4.Demibold.Promotions,
            MiuixIcons.Os4.Demibold.Read,
            MiuixIcons.Os4.Demibold.Recent,
            MiuixIcons.Os4.Demibold.Recording,
            MiuixIcons.Os4.Demibold.RecordingTape,
            MiuixIcons.Os4.Demibold.Redo,
            MiuixIcons.Os4.Demibold.Refresh,
            MiuixIcons.Os4.Demibold.Remove,
            MiuixIcons.Os4.Demibold.RemoveContact,
            MiuixIcons.Os4.Demibold.Rename,
            MiuixIcons.Os4.Demibold.Replace,
            MiuixIcons.Os4.Demibold.Reply,
            MiuixIcons.Os4.Demibold.ReplyAll,
            MiuixIcons.Os4.Demibold.Report,
            MiuixIcons.Os4.Demibold.Reset,
            MiuixIcons.Os4.Demibold.Rocket,
            MiuixIcons.Os4.Demibold.RotateLeft,
            MiuixIcons.Os4.Demibold.Save,
            MiuixIcons.Os4.Demibold.Scan,
            MiuixIcons.Os4.Demibold.ScreenCapture,
            MiuixIcons.Os4.Demibold.ScreenMirroring,
            MiuixIcons.Os4.Demibold.Search,
            MiuixIcons.Os4.Demibold.SearchDevice,
            MiuixIcons.Os4.Demibold.SelectAll,
            MiuixIcons.Os4.Demibold.Send,
            MiuixIcons.Os4.Demibold.Settings,
            MiuixIcons.Os4.Demibold.Share,
            MiuixIcons.Os4.Demibold.ShortVideo,
            MiuixIcons.Os4.Demibold.Show,
            MiuixIcons.Os4.Demibold.Sidebar,
            MiuixIcons.Os4.Demibold.Sort,
            MiuixIcons.Os4.Demibold.Starred,
            MiuixIcons.Os4.Demibold.Stopwatch,
            MiuixIcons.Os4.Demibold.Store,
            MiuixIcons.Os4.Demibold.Tasks,
            MiuixIcons.Os4.Demibold.Th1,
            MiuixIcons.Os4.Demibold.Th10,
            MiuixIcons.Os4.Demibold.Th11,
            MiuixIcons.Os4.Demibold.Th12,
            MiuixIcons.Os4.Demibold.Th13,
            MiuixIcons.Os4.Demibold.Th14,
            MiuixIcons.Os4.Demibold.Th15,
            MiuixIcons.Os4.Demibold.Th16,
            MiuixIcons.Os4.Demibold.Th17,
            MiuixIcons.Os4.Demibold.Th18,
            MiuixIcons.Os4.Demibold.Th19,
            MiuixIcons.Os4.Demibold.Th2,
            MiuixIcons.Os4.Demibold.Th20,
            MiuixIcons.Os4.Demibold.Th21,
            MiuixIcons.Os4.Demibold.Th22,
            MiuixIcons.Os4.Demibold.Th23,
            MiuixIcons.Os4.Demibold.Th24,
            MiuixIcons.Os4.Demibold.Th25,
            MiuixIcons.Os4.Demibold.Th26,
            MiuixIcons.Os4.Demibold.Th27,
            MiuixIcons.Os4.Demibold.Th28,
            MiuixIcons.Os4.Demibold.Th29,
            MiuixIcons.Os4.Demibold.Th3,
            MiuixIcons.Os4.Demibold.Th30,
            MiuixIcons.Os4.Demibold.Th31,
            MiuixIcons.Os4.Demibold.Th4,
            MiuixIcons.Os4.Demibold.Th5,
            MiuixIcons.Os4.Demibold.Th6,
            MiuixIcons.Os4.Demibold.Th7,
            MiuixIcons.Os4.Demibold.Th8,
            MiuixIcons.Os4.Demibold.Th9,
            MiuixIcons.Os4.Demibold.Theme,
            MiuixIcons.Os4.Demibold.Timer,
            MiuixIcons.Os4.Demibold.TopDownloads,
            MiuixIcons.Os4.Demibold.Translate,
            MiuixIcons.Os4.Demibold.Trim,
            MiuixIcons.Os4.Demibold.Tune,
            MiuixIcons.Os4.Demibold.Undo,
            MiuixIcons.Os4.Demibold.Unlock,
            MiuixIcons.Os4.Demibold.Unpin,
            MiuixIcons.Os4.Demibold.Unstar,
            MiuixIcons.Os4.Demibold.Update,
            MiuixIcons.Os4.Demibold.UploadCloud,
            MiuixIcons.Os4.Demibold.VerticalSplit,
            MiuixIcons.Os4.Demibold.VolumeOff,
            MiuixIcons.Os4.Demibold.VolumeUp,
            MiuixIcons.Os4.Demibold.Weeks,
            MiuixIcons.Os4.Demibold.WorldClock,
            MiuixIcons.Os4.Demibold.Years,
            MiuixIcons.Os4.Demibold.ZoomOut,
        ),
    )
}
